<a href="https://colab.research.google.com/github/Maryam-Taherzadeh/Computational-Drug-Discovery/blob/main/problem_01_qsar/notebooks/mdm2_part1_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Computational Drug Discovery [Part 1] Download Bioactivity Data**

## Project Overview

In this Jupyter Notebook, we develop a real-world data science project focused on drug discovery. The goal is to build a machine learning model using bioactivity data obtained from the ChEMBL database.

This project demonstrates how computational methods can be applied to predict the biological activity of chemical compounds, enabling more efficient identification of potential drug candidates.

## Objectives

- Retrieve and preprocess bioactivity data from ChEMBL
- Convert molecular structures (SMILES) into numerical features using RDKit
- Perform exploratory data analysis (EDA)
- Train machine learning models to predict molecular activity (e.g., IC50)
- Evaluate model performance using appropriate metrics

## Applications

This workflow is widely used in:
- Drug discovery
- QSAR/QSPR modeling
- Virtual screening pipelines

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

---

### **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**
###Install ChEMBL Web Resource Client

In this step, we install the ChEMBL web resource client, which allows us to retrieve bioactivity data directly from the ChEMBL.

This client provides a convenient interface to access:

* molecular data
* bioactivity data (e.g., IC50)
* target information

In [5]:
! pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in /usr/local/lib/python3.12/dist-packages (0.10.9)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Requirement already satisfied: requests-cache~=1.2 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.3.1)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.2.25)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.9.6)
Requirement already satisfied: url-normalize>=2.0 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (2.2.1)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)

## **Importing libraries**

In [10]:
# Import necessary libraries

import pandas as pd
!pip install chembl_webresource_client --upgrade
from chembl_webresource_client.new_client import new_client

Requirement already satisfied: chembl_webresource_client in /usr/local/lib/python3.12/dist-packages (0.10.9)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Requirement already satisfied: requests-cache~=1.2 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.3.1)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.2.25)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.9.6)
Requirement already satisfied: url-normalize>=2.0 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (2.2.1)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)

## **Search for Target protein**

## **Search for MDM2**

In [13]:
target = new_client.target
target_query = target.search('MDM2')
targets = pd.DataFrame.from_dict(target_query)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,E3 ubiquitin-protein ligase Mdm2,18.0,False,CHEMBL5023,"[{'accession': 'Q00987', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Canis lupus familiaris,E3 ubiquitin-protein ligase Mdm2,18.0,False,CHEMBL3600278,"[{'accession': 'P56950', 'component_descriptio...",SINGLE PROTEIN,9615
2,[],Mus musculus,E3 ubiquitin-protein ligase Mdm2,18.0,False,CHEMBL3600279,"[{'accession': 'P23804', 'component_descriptio...",SINGLE PROTEIN,10090
3,[],Homo sapiens,Protein cereblon/E3 ubiquitin-protein ligase Mdm2,18.0,False,CHEMBL4523702,"[{'accession': 'Q00987', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
4,[],Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,17.0,False,CHEMBL1907611,"[{'accession': 'P04637', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
5,[],Homo sapiens,Casein kinase I/MDM2,17.0,False,CHEMBL3038493,"[{'accession': 'Q00987', 'component_descriptio...",PROTEIN COMPLEX,9606
6,[],Homo sapiens,MDM2-MDMX,17.0,False,CHEMBL4106123,"[{'accession': 'Q00987', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
7,[],Homo sapiens,E3 ubiquitin-protein ligase Mdm2/CDK6,17.0,False,CHEMBL4523718,"[{'accession': 'Q00987', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
8,[],Homo sapiens,BRD4/E3 ubiquitin-protein ligase Mdm2,17.0,False,CHEMBL4523719,"[{'accession': 'Q00987', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
9,[],Homo sapiens,Protein cereblon/Tumour suppressor p53/oncopro...,17.0,False,CHEMBL4879538,"[{'accession': 'P04637', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
10,[],Homo sapiens,von Hippel-Lindau disease tumor suppressor/E3 ...,17.0,False,CHEMBL5291692,"[{'accession': 'Q00987', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
11,[],Homo sapiens,MDM2-HDAC3,17.0,False,CHEMBL5465251,"[{'accession': 'Q00987', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
12,[],Homo sapiens,MDM2-HDAC1,17.0,False,CHEMBL5465382,"[{'accession': 'Q00987', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
13,[],Homo sapiens,MDM2-HDAC2,17.0,False,CHEMBL5465383,"[{'accession': 'Q00987', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
14,[],Homo sapiens,MDM2/MDMX-p53,16.0,False,CHEMBL3883306,"[{'accession': 'P04637', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
15,[],Homo sapiens,GSPT1/E3 ubiquitin-protein ligase Mdm2,16.0,False,CHEMBL4523720,"[{'accession': 'Q00987', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606
16,[],Homo sapiens,DNA damage-binding protein 1/Protein cereblon/...,14.0,False,CHEMBL4888446,"[{'accession': 'Q00987', 'component_descriptio...",PROTEIN COMPLEX,9606
17,[],Homo sapiens,Protein Mdm4,11.0,False,CHEMBL1255126,"[{'accession': 'O15151', 'component_descriptio...",SINGLE PROTEIN,9606
18,[],Homo sapiens,Tumour suppressor protein p53/Mdm4,9.0,False,CHEMBL2221344,"[{'accession': 'P04637', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606

# Select and retrieve bioactivity data for MDM2-p53 interaction target

---

We will assign the fifth entry (which corresponds to the target protein, *tumour suppressor p53/oncoprotein Mdm2*) to the **selected_target** variable.

In [20]:
selected_target = targets.target_chembl_id[4]
selected_target

'CHEMBL1907611'

Here, we retrieve bioactivity data for the *p53–MDM2 interaction target* (CHEMBL1907611), focusing on compounds with experimentally measured **IC50 values reported in nanomolar (nM) units**, which will be used to assess inhibitory activity.

In [21]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [22]:
df = pd.DataFrame.from_dict(res)

In [189]:
df.head(10)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1424130,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 inte...,B,None,None,BAO_0000190,BAO_0000219,cell-based format,CCCN1C(=O)c2ccccc2C1(NC(=O)c1ccc(C(C)(C)C)cc1)...,None,None,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '7.98', 'le': None, 'lle': None, 'sei'...",CHEMBL179549,None,CHEMBL179549,4.57,0,http://www.openphacts.org/units/Nanomolar,366176,=,1,1,=,None,IC50,nM,None,27000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,None,None,IC50,uM,UO_0000065,None,27.0
1,None,None,1424131,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 inte...,B,None,None,BAO_0000190,BAO_0000219,cell-based format,CCCN1C(=O)c2ccccc2C1(NC(=O)c1ccccc1)c1ccc(C(C)...,None,None,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '9.80', 'le': '0.18', 'lle': '-1.30', ...",CHEMBL360920,None,CHEMBL360920,4.18,0,http://www.openphacts.org/units/Nanomolar,366182,=,1,1,=,None,IC50,nM,None,66000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,None,None,IC50,uM,UO_0000065,None,66.0
2,None,None,1424132,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 inte...,B,None,None,BAO_0000190,BAO_0000219,cell-based format,CCCOC1(c2ccccc2)c2ccccc2C(=O)N1C(Cc1ccc(O)cc1)...,None,None,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '9.08', 'le': '0.17', 'lle': '-0.21', ...",CHEMBL182052,None,CHEMBL182052,4.05,0,http://www.openphacts.org/units/Nanomolar,366189,=,1,1,=,None,IC50,nM,None,90000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,None,None,IC50,uM,UO_0000065,None,90.0
3,None,None,1424135,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 inte...,B,None,None,BAO_0000190,BAO_0000219,cell-based format,OCC(NC1(c2ccccc2)c2ccccc2CC1Cc1ccccc1)C(O)c1cc...,None,None,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '9.05', 'le': '0.16', 'lle': '-0.96', ...",CHEMBL179662,None,CHEMBL179662,4.07,0,http://www.openphacts.org/units/Nanomolar,366201,=,1,1,=,None,IC50,nM,None,85000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,None,None,IC50,uM,UO_0000065,None,85.0
4,None,None,1424136,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 inte...,B,None,None,BAO_0000190,BAO_0000219,cell-based format,CC(C)(C)c1ccc(COC2(c3ccccc3)c3ccccc3C(=O)N2Cc2...,None,None,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '8.74', 'le': '0.16', 'lle': '-3.02', ...",CHEMBL181688,None,CHEMBL181688,4.04,0,http://www.openphacts.org/units/Nanomolar,366206,=,1,1,=,None,IC50,nM,None,92000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,None,None,IC50,uM,UO_0000065,None,92.0
5,None,None,1424137,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 inte...,B,None,None,BAO_0000190,BAO_0000219,cell-based format,COc1ccc(C(O)CNC2(c3ccccc3)c3ccccc3C(=O)N2Cc2cc...,None,None,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '8.94', 'le': '0.16', 'lle': '-0.73', ...",CHEMBL179114,None,CHEMBL179114,4.16,0,http://www.openphacts.org/units/Nanomolar,366211,=,1,1,=,None,IC50,nM,None,70000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,None,None,IC50,uM,UO_0000065,None,70.0
6,None,None,1424233,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 inte...,B,None,None,BAO_0000190,BAO_0000219,cell-based format,O=C1c2ccccc2C(OCCCO)(c2ccc(Cl)cc2)N1Cc1ccccc1,None,None,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '11.76', 'le': '0.23', 'lle': '0.20', ...",CHEMBL360719,None,CHEMBL360719,4.80,0,http://www.openphacts.org/units/Nanomolar,366216,=,1,1,=,None,IC50,nM,None,15900.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,None,None,IC50,uM,UO_0000065,None,15.9
7,None,None,1424234,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 inte...,B,None,None,BAO_0000190,BAO_0000219,cell-based format,CC(C)(C)c1ccc(COC2(c3ccccc3)c3ccccc3C(=O)N2Cc2...,None,None,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '8.74', 'le': '0.16', 'lle': '-3.02', ...",CHEMBL181688,None,CHEMBL181688,4.04,0,http://www.openphacts.org/units/Nanomolar,366222,=,1,1,=,None,IC50,nM,None,92000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,None,None,IC50,uM,UO_0000065,None,92.0
8,None,None,1424235,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 inte...,B,None,None,BAO_0000190,BAO_0000219,cell-based format,CC(=O)NCCN1C(=O)c2ccccc2C1(OCc1ccc(C(C)(C)C)cc...,None,None,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '10.63', 'le': '0.19', 'lle': '-0.14',...",CHEMBL360141,None,CHEMBL360141,4.85,0,http://www.openphacts.org/units/Nanomolar,366227,=,1,1,=,None,IC50,nM,None,14000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,None,None,IC50,uM,UO_0000065,None,14.0
9,None,None,1424236,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 inte...,B,None,None,BAO_0000190,BAO_0000219,cell-based format,O=C1c2ccccc2C(OCCc2ccccn2)(c2ccc(Cl)cc2)N1Cc1c...,None,None,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '10.07', 'le': '0.19', 'lle': '-1.27',...",CHEMBL361115,None,CHEMBL361115,4.58,0,http://www.openphacts.org/units/Nanomolar,366233,=,1,1,=,None,IC50,nM,None,26200.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,None,None,IC50,uM,UO_0000065,None,26.2

In [25]:
#It returns all different activity types in your dataset.
df.standard_type.unique()

array(['IC50'], dtype=object)

In [26]:
df.shape

(1820, 46)

Finally we will save the resulting bioactivity data to a CSV file **mdm2_data.csv**.

In [89]:
# save it locally
df.to_csv('mdm2_data.csv', index=False)

## **Copying files to Google Drive**

Firstly, we need to mount the Google Drive into Colab so that we can have access to our Google adrive from within Colab.

In [157]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

Next, we create a **data** folder in our **Colab Notebooks** folder on Google Drive.

In [171]:
# create folder safely
!mkdir -p "/content/gdrive/My Drive/Colab Notebooks/data2"
# copy file into folder
!cp mdm2_data.csv "/content/gdrive/My Drive/Colab Notebooks/data2"
# list files
!ls "/content/gdrive/My Drive/Colab Notebooks/data2"
# show detail info
!ls -l "/content/gdrive/My Drive/Colab Notebooks/data"
!pwd

mdm2_data.csv
total 175
-rw------- 1 root root 178896 Apr 16 00:41 mdm2_preprocessed_data.csv
/content

Let's see the CSV files that we have so far.

In [170]:

!ls

gdrive	mdm2_data.csv  mdm2_preprocessed_data.csv  sample_data

Taking a glimpse of the **mdm2_data.csv.csv** file that we've just created.

In [188]:
! head mdm2_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,1424130,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 interaction in SJSA human sarcoma cells,B,,,BAO_0000190,BAO_0000219,cell-based format,CCCN1C(=O)c2ccccc2C1(NC(=O)c1ccc(C(C)(C)C)cc1)c1ccc(OCOCC[Si](C)(C)C)cc1,,,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '7.98', 'le': None, 'lle': None, 'sei': None}",CHEMBL179549,,CHEMBL179549,4.57,0,http://www.openphacts.org/units/Nanomolar,366176,=,1,1,=,,IC50,nM,,27000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,,,IC50,uM,UO_0000065,,27.0
,,1424131,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 interaction in SJSA human sarcoma cells,B,,,BAO_0000190,BAO_0000219,cell-based format,CCCN1C(=O)c2ccccc2C1(NC(=O)c1ccccc1)c1ccc(C(C)(C)C)cc1,,,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '9.80', 'le': '0.18', 'lle': '-1.30', 'sei': '8.46'}",CHEMBL360920,,CHEMBL360920,4.18,0,http://www.openphacts.org/units/Nanomolar,366182,=,1,1,=,,IC50,nM,,66000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,,,IC50,uM,UO_0000065,,66.0
,,1424132,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 interaction in SJSA human sarcoma cells,B,,,BAO_0000190,BAO_0000219,cell-based format,CCCOC1(c2ccccc2)c2ccccc2C(=O)N1C(Cc1ccc(O)cc1)C(=O)OC,,,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '9.08', 'le': '0.17', 'lle': '-0.21', 'sei': '5.32'}",CHEMBL182052,,CHEMBL182052,4.05,0,http://www.openphacts.org/units/Nanomolar,366189,=,1,1,=,,IC50,nM,,90000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,,,IC50,uM,UO_0000065,,90.0
,,1424135,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 interaction in SJSA human sarcoma cells,B,,,BAO_0000190,BAO_0000219,cell-based format,OCC(NC1(c2ccccc2)c2ccccc2CC1Cc1ccccc1)C(O)c1ccccc1,,,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '9.05', 'le': '0.16', 'lle': '-0.96', 'sei': '7.75'}",CHEMBL179662,,CHEMBL179662,4.07,0,http://www.openphacts.org/units/Nanomolar,366201,=,1,1,=,,IC50,nM,,85000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,,,IC50,uM,UO_0000065,,85.0
,,1424136,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 interaction in SJSA human sarcoma cells,B,,,BAO_0000190,BAO_0000219,cell-based format,CC(C)(C)c1ccc(COC2(c3ccccc3)c3ccccc3C(=O)N2Cc2ccccc2)cc1,,,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '8.74', 'le': '0.16', 'lle': '-3.02', 'sei': '13.66'}",CHEMBL181688,,CHEMBL181688,4.04,0,http://www.openphacts.org/units/Nanomolar,366206,=,1,1,=,,IC50,nM,,92000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,,,IC50,uM,UO_0000065,,92.0
,,1424137,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 interaction in SJSA human sarcoma cells,B,,,BAO_0000190,BAO_0000219,cell-based format,COc1ccc(C(O)CNC2(c3ccccc3)c3ccccc3C(=O)N2Cc2ccccc2)cc1,,,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '8.94', 'le': '0.16', 'lle': '-0.73', 'sei': '6.72'}",CHEMBL179114,,CHEMBL179114,4.16,0,http://www.openphacts.org/units/Nanomolar,366211,=,1,1,=,,IC50,nM,,70000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,,,IC50,uM,UO_0000065,,70.0
,,1424233,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 interaction in SJSA human sarcoma cells,B,,,BAO_0000190,BAO_0000219,cell-based format,O=C1c2ccccc2C(OCCCO)(c2ccc(Cl)cc2)N1Cc1ccccc1,,,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '11.76', 'le': '0.23', 'lle': '0.20', 'sei': '9.64'}",CHEMBL360719,,CHEMBL360719,4.80,0,http://www.openphacts.org/units/Nanomolar,366216,=,1,1,=,,IC50,nM,,15900.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,,,IC50,uM,UO_0000065,,15.9
,,1424234,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 interaction in SJSA human sarcoma cells,B,,,BAO_0000190,BAO_0000219,cell-based format,CC(C)(C)c1ccc(COC2(c3ccccc3)c3ccccc3C(=O)N2Cc2ccccc2)cc1,,,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '8.74', 'le': '0.16', 'lle': '-3.02', 'sei': '13.66'}",CHEMBL181688,,CHEMBL181688,4.04,0,http://www.openphacts.org/units/Nanomolar,366222,=,1,1,=,,IC50,nM,,92000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,,,IC50,uM,UO_0000065,,92.0
,,1424235,[],CHEMBL828042,Inhibitory concentration against MDM2-p53 interaction in SJSA human sarcoma cells,B,,,BAO_0000190,BAO_0000219,cell-based format,CC(=O)NCCN1C(=O)c2ccccc2C1(OCc1ccc(C(C)(C)C)cc1)c1ccccc1,,,CHEMBL1142026,Bioorg Med Chem Lett,2005,"{'bei': '10.63', 'le': '0.19', 'lle': '-0.14', 'sei': '8.28'}",CHEMBL360141,,CHEMBL360141,4.85,0,http://www.openphacts.org/units/Nanomolar,366227,=,1,1,=,,IC50,nM,,14000.0,CHEMBL1907611,Homo sapiens,Tumour suppressor p53/oncoprotein Mdm2,9606,,,IC50,uM,UO_0000065,,14.0

## **Handling missing data**
If any compounds has missing value for the **standard_value** column then drop it

In [100]:
df.standard_value.isna().sum()

np.int64(0)

In [102]:
df2 = df[df.standard_value.notna()]

Apparently, for this dataset there is no missing data. But we can use the above code cell for bioactivity data of other target protein.

## **Data pre-processing of the bioactivity data**

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [187]:
bioactivity_class = []
for i in df2.standard_value:
  if float(i) >= 10000:
    bioactivity_class.append("inactive")
  elif float(i) <= 1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

### **Iterate the *molecule_chembl_id* to a list**

In [185]:
mol_cid = []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

### **Iterate *canonical_smiles* to a list**

In [184]:
canonical_smiles = []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

### **Iterate *standard_value* to a list**

In [183]:
standard_value = []
for i in df2.standard_value:
  standard_value.append(i)

### **Combine the 4 lists into a dataframe**

In [120]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))

df3 = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])

Saves dataframe to CSV *file*

In [191]:
df3.to_csv('mdm2_preprocessed_data.csv', index=False)

In [192]:
! ls -l

total 2556
drwx------ 5 root root    4096 Apr 16 00:41 gdrive
-rw-r--r-- 1 root root 2427770 Apr 15 16:53 mdm2_data.csv
-rw-r--r-- 1 root root  178896 Apr 16 01:50 mdm2_preprocessed_data.csv
drwxr-xr-x 1 root root    4096 Apr  2 13:31 sample_data

Let's copy to the Google Drive

In [193]:
! cp mdm2_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"
! cp mdm2_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [194]:
! ls "/content/gdrive/My Drive/Colab Notebooks/data"

mdm2_data.csv  mdm2_preprocessed_data.csv

---